#!/bin/bash

print_help() {
    echo "idk figure it out"
cat << EOF
Usage: ${0##*/} [options]

This script is meant to simplify making plots with gnuplot.

Options:
  -h          Display this help and exit
  -d          The datafile that will be used for ploting. Defaults to data.txt
  -T          The title of the plot
  -X          The x label
  -Y          The ylabe
  -x          The horizontal size of the plot in pixels or characters
  -y          The verticle size of the plot in pixels or characters
  -o          The file where the plot would be saved
  -t          The terminal to use for rendering the output. Defaults to pngcairo. Some other nice ones are cairolatex or dumb
  -f          If the first column is time, you can use this to specify the input format of the time
  -F          The is used to format the time for output
  -S          If the separator isn't a space, use this to set the separator
  -n          If the data has only one column, use this flag
  -c          If there is more than two columns, us this to specify how many should be plotted

EOF

}

qplot_opts=":d:t:s:o:x:y:X:Y:T:F:f:S:nhc:"
data_file="data.txt"
plot_title="QPlot Data"
x_label=""
y_label=""
x_dim="1920"
y_dim="1080"
out_file=""
terminal="pngcairo"
time_format=""
no_index=""
col_count=""
out_time_format="%m/%d/%Y %H:%M:%S"
datafile_separator=""

while getopts $qplot_opts opt; do
    case "$opt" in
        h)
            print_help
            exit
            ;;
        d)
            data_file="$OPTARG"
            ;;
        T)
            plot_title="$OPTARG"
            ;;
        X)
            x_label="$OPTARG"
            ;;
        Y)
            y_label="$OPTARG"
            ;;
        x)
            x_dim="$OPTARG"
            ;;
        y)
            y_dim="$OPTARG"
            ;;
        o)
            out_file="$OPTARG"
            ;;
        t)
            terminal="$OPTARG"
            ;;
        f)
            time_format="$OPTARG"
            ;;
        F)
            out_time_format="$OPTARG"
            ;;
        S)
            datafile_separator="$OPTARG"
            ;;
        n)
            no_index="true"
            ;;
        c)
            col_count="$OPTARG"
            ;;
        :)
            echo "Option -${OPTARG} requires an argument."
            exit 1
            ;;
        ?)
        echo "Invalid option: -$OPTARG."
        exit 1
        ;;
    esac
done

get_gnuplot_script() {
    resp=""

    if [[ $datafile_separator != "" ]]; then
        resp+="set datafile separator \"$datafile_separator\"; "
    fi

    if [[ "$terminal" == "pngcairo" ]]; then
        resp+="set terminal pngcairo size $x_dim,$y_dim; "
    elif [[ "$terminal" == "dumb" ]]; then
        resp+="set terminal dumb size $x_dim,$y_dim; "
    fi

    if [[ $out_file != "" ]]; then
        resp+="set output '$out_file'; "
    fi

    if [[ $time_format != "" ]]; then
        resp+="set xdata time; "
        resp+="set timefmt \"$time_format\"; "
        resp+="set format x \"$out_time_format\"; "
    fi

    using_arg="1:2"
    if [[ $no_index == "true" ]]; then
        using_arg="1"
    fi

    resp+="set title \"$plot_title\"; "
    resp+="set ylabel '$y_label'; "
    resp+="set xlabel '$x_label'; "

    if [[ $col_count != "" ]]; then
        using_arg="1:$col_count"
        resp+="set key autotitle columnhead; "
        resp+="plot for [i=2:$col_count] '$data_file' using 1:i with lines title columnhead(i); "
    else
        resp+="plot '$data_file' using $using_arg with lines title ''; "
    fi


    echo $resp
}

render_single_plot() {
    echo "Plotting $data_file in $out_file" 1>&2

    gnuScript=$(get_gnuplot_script)
    echo -e $gnuScript 1>&2

    gnuplot -e "$gnuScript"
}


render_single_plot
